name: stock_management_with_riverpod
description: A Flutter application for managing product stocks with efficient state management using Riverpod.
version: 1.0.0+1
publish_to: 'none' # This app is not published on pub.dev

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  # Core Flutter SDK
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: any # Efficient, reactive state management solution.

  # Database and Storage
  sqflite: any # SQLite database package for Flutter.
  path: any # Handles file paths for database storage.

  # UI and Design
  cupertino_icons: ^1.0.8 # Provides Cupertino-style icons for iOS compatibility.
  google_fonts: any # For using Google Fonts to style text and themes.

  # Utilities
  intl: any # For formatting dates, numbers, and currencies.
  flutter_localization: any # Enables localization for supporting multiple languages.
  flutter_screenutil: any # Use the latest version
  dropdown_button2: any # Enhanced DropdownButton with additional customization options like rounded corners, searchable menus, and flexible layouts.

dev_dependencies:
  flutter_test:
    sdk: flutter # Tools for testing Flutter applications.
  flutter_lints: ^4.0.0 # Recommended lints for better code quality.

flutter:
  uses-material-design: true # Enables Material Design icons and themes.

  # Add assets section if you have images or other resources.
  # assets:
  #   - assets/images/

  # Add fonts section if you are using custom fonts.
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
